version: '3.5'

services:

    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}_laravel:latest
      build:
        context: .
        args:
          - "BUILD_ARGUMENT_ENV=dev"
          - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_laravel
      expose:
        - 80
        - 443
      ports:
        - 80:80
        - 443:443
      volumes:
        - .:/var/www/html
      depends_on:
        - mysql
      networks:
        - laravel

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=larablog
      ports:
        - 33061:3306
      volumes:
        - ./storage/mysql-data:/var/lib/mysql
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - laravel

networks:
  laravel:
    name: laravel
